apiVersion: v1
kind: Namespce
metadata:
  name: app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: app
spec:
  replicas: 2
  selector:
    matchLebels:
      app: hello-app
    template:
      metadata:
        labels:
          app: hello
      spec:
        containers:
        - name: nginx
          image: public.ecr.aws/nginx/nginx:latest
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: app
spec:
  selector:
    app: hello
  type: LoadBalancer
  ports:
   - protocol: TCP
     port: 80
     targetPort: 80